name: myinfraworkflow

on:
#workflow_dispatch:
  push:
    branches:
      - main
      - feature
      - testbug
  pull_request:
    branches:
      - main

permissions: 
  contents: read
  id-token: write

jobs:
  TerraformInstall:
    runs-on: self-hosted
    steps:
      - name: Terraform installer
        uses: autero1/action-terraform@v3.0.1          
        with:
          terraform_version: 1.7.5



